### ISSUE TITLE
Define DSL to parse data into JSON

### ISSUE THREAD

**Issue by clemsos** [clemsos/wiki-plugin-map#1]

**Comment by opn** [comment]
We can leave this til we have plenty of data and worked with transporters and different use cases. I also thin @wardcunningham can advise / add the DSL coding once we have the requirements and json data structures in place?

**Comment by clemsos** [comment]
Great. I will advise to use existing standards to store geo information, namely [GEOJson](http://geojson.org/). It supports markers, captions, icons, polygons, etc and will integrate flawlessly with leaflet / OSM layers. You can see examples on this page http://leafletjs.com/examples/geojson.html

**Comment by clemsos** [comment]
This package make it quite simple https://www.npmjs.com/package/geojson

**Comment by WardCunningham** [comment]
The map plugin could simply look for a `geo` field in the item and then render that as geojson with the map oriented as appropriate. A separate markup for configuring the map would still be useful but not necessary if the maps come from transporters. (see below)

A map might look left for other items identified as `geo-source` and then query and merge their geojson. This idiom has been documented elsewhere. `radar-source` is the first such identification so look for examples that respond to this. Images that have been geo-tagged could be geo-sources.

The text field could be scanned for lines that match various regex for coordinates. Here are simple rules:

* lines with ALL CAPS keywords are reserved for commands.
* lines with recognizable coordinates are markers, labeled with subsequent text to end of line.
* remaining non-blank lines are collected as the map's caption.

**Comment by opn** [comment]
How about a three-way pair programming session :)

   - I'll work on the Map transporter I've started that extracts GPS
   formation from images, and uploads to wiki (and later IPFS).
   - Ward maybe you can hack / show us how to do the DSL parsing in wiki,
   and the data aggregation logic
   - Clement integrates the geojson standard and leaflet rendering

We got a Hangout tonight - you available Clement? Otherwise maybe we can
aim to spread the knowledge this weekend - 5pm Saturday GMT.

**Comment by clemsos** [comment]
@WardCunningham sounds like a good plan. It may be interesting to support other geojson features as well, like Line, Polygon, etc.

at what time is the hangout tonight ?

**Comment by opn** [comment]
6PM GMT - so in just over an hour.

**Comment by WardCunningham** [comment]
I'm happy to do parser. Here is guidance I have written and would intend to follow.
http://plugins.fed.wiki.org/common-markup-practice.html

If we were to plot travel tracks on maps then I would favor having a Track plugin that would represent them as an item. The default rendering might just be the total length and possibly elevation gain if that were available. A Track would announce that it was a geo-source and would render its track in geojson when asked. I could pull up pages with tracks for bike tours I might be recommending for you. The last page would be a map that would show all three tracks. 

We could expect a Track or any other geo-source to expose a bounding region as metadata in the sitemap. Then a map could be configured to search the neighborhood for all pages intersecting its view. The map would then render these on the map with click-to-view that would add the source page to the lineup.

Let's reserve Map markup to be mostly about configuring this sort of behavioral choices.

**Comment by WardCunningham** [comment]
On Jun 22, 2016, at 8:50 AM, David Bovill <notifications@github.com> wrote:

I'm in the hangout now.

> 6PM GMT - so in just over an hour.
> > at what time is the hangout tonight ?

**Comment by bracken** [comment]
Sitting here with Ward, The 2 starter regexes http://www.rubular.com/r/xEShwb0Til http://www.rubular.com/r/FKfYDEYWCk

**Comment by WardCunningham** [comment]
@bracken and I met at wiki's birthday party this spring.
http://ward.bay.wiki.org/wiki-turns-21.html

We met again at the Open-Source Bridge hacker lounge last evening and started working on a map markup along the lines suggested above.
http://opensourcebridge.org/wiki/2016/Hacker_Lounge

We looked for sample coordinates as they might appear in the wild. We sought two distinctly different samples and found both the first place we looked, a random click on a map of Portland. These spanned the spectrum from direct to ornate.
![image](https://cloud.githubusercontent.com/assets/12127/16305792/30d38ebe-3910-11e6-8739-2ac9cf1dcadd.png)

We started coding on  the @clemsos fork. I worked on the grunt script while Bracken wrote regex for these two formats. I added a new stub for the markup parser and exposed it to a Mocha test script with alternative exports.

```
window.plugins.map = {emit, bind} if window?
module.exports = {parse} if module?
```

We saw our work come together when the first test passed. Then off to dinner.

I mention all of this because indentation changes touch pretty much every line of coffeescript in the plugin. I hope to write a few more tests and have a pull request this morning. I will direct that to this repo which will take some thinking on my part. I thought you should know what is coming.

**Comment by opn** [comment]
Here is the state of the new map-transport:

   - http://plugin.fedwiki.org/map-transport.html

I also have to dig around looking at common formats from gps info in photos
to the way url's are encoded. I wish we could re-use this logic - some day
:)

**Comment by WardCunningham** [comment]
More thinking about maps and places:
http://ward.asia.wiki.org/maps-and-places.html

**Comment by opn** [comment]
I forked that page and added some info:

   - http://plugin.fedwiki.org/maps-and-places.html

At first glance at the options described, I feel we should look at using
our own decentralised storage model in wiki, possibly leveraging the D3
libraries, though I would have thought sticking with the Leaflet and
OpenStreetMap approach seems the strongest?

**Comment by WardCunningham** [comment]
Yes, Leaflet for sure. And d3 in its own plugins.

**Comment by clemsos** [comment]
Cool progresses here ! I didn't have any time but will do next week. 

About d3, it can be used to draw on leaflet maps as well but this seems over kill for the need of the plugin right now. Just do leaflet seems better.

**Comment by WardCunningham** [comment]
I think we've met the expectation of this issue. I will continue working on more specific requests in other issues. We should aim towards improvements that can be integrated into the standard wiki package soon. Mostly this means respecting older map parameters when newer markup has not been provided.
