### ISSUE TITLE
Click on markers should show a bubble

### ISSUE THREAD

**Issue by clemsos** [clemsos/wiki-plugin-map#3]

**Comment by clemsos** [comment]
the popup has already been added in #7 . I added ability to accept html and wiki syntax in the markers popup in a8c5403bbe3286e86ecf646d00b93d5aca3d1c2b but I add to un-escape the HTML, so unsure how safe it is.

**Comment by WardCunningham** [comment]
Our normal markup establishes special meaning to only two unlikely sequence. 

```
[[ ... ]]
[http ... ]
```

The resolve function calls wiki.resolveLinks to converts this to internal or external hyperlinks in the form handled by our javascript. It has already been applied by the time I .bindPopup(p.label) Link resolution works in several stages so that html meaningful characters are escaped but the html to create links is not.

Reading your commit, it appears to furnther strip out without replacement both surviving wiki and html markup. Is there some reason to not have links in popup text? Do our two separate calls to wiki.resolveLinks interfere? Or am I misinterpreting the code?

**Comment by WardCunningham** [comment]
This issue has been resolved. 

@clemsos, I'm still confused as to why we are encoding an extra time just to decode the marker labels again. It seems to be a no-op so I left it in. I'd like to better understand your intention.
